print("Getting to know you!")
print()
yourName = input("What is your name?: ")
yourFood = input("What do you likke to eat?: ")
yourMusic = input("Whose music are you listening to these days?: ")
yourLocation = input("Where is your house?: ")
print("You are")
print(yourName)
print("You are always hungry for")
print(yourFood)
print("You get your groove on with")
print(yourMusic)
print("Live in amazing")
print(yourLocation)