food = input("Name a food ")
plant = input("Name a type of plant ")
method = input("Name a method of cooking ")
describe = input("What word describes burned food? ")
diyItem = input("Name a DIY item ")
print()
print("MENU")
print(method, food, "with", describe, plant, "on a bed of", diyItem)